---
- name: set subject alt name for Google Chrome 58 or more
  blockinfile:
    path: /etc/pki/tls/openssl.cnf
    block: |
      subjectAltName=DNS:*.{{ roles_common_domain_name }}
    insertafter: \[\susr_cert\s\]

- name: certificate authority for identify server
  command: >
    openssl ca -batch
    -in {{ path_file_certificate_server_request }}
    -cert {{ path_file_certificate_self }}
    -out {{ path_file_certificate_server }}
    -days 36500
  args:
    creates: '{{ path_file_certificate_server }}'
