---
- name: ensure certificate authority directory defined as default on /etc/pki/tls/openssl.cnf
  file:
    path: /etc/pki/CA
    state: directory
    group: root
    owner: root
    mode: 0755

- name: ensure private certificate authority directory defined as default on /etc/pki/tls/openssl.cnf
  file:
    path: /etc/pki/CA/private
    state: directory
    group: root
    owner: root
    mode: 0700

- name: ensure new certificate authority directory defined as default on /etc/pki/tls/openssl.cnf
  file:
    path: /etc/pki/CA/newcerts
    state: directory
    group: root
    owner: root
    mode: 0755

- name: create key for certificate authority
  include_tasks: create_key_without_passphrase.yml
  vars:
    path_key: '{{ path_file_secret_key_certificate_authority }}'

- name: create certificate signing request
  command: >
    openssl req -new
    -key {{ path_file_secret_key_certificate_authority }}
    -out {{ path_file_certificate_server_request_certificate_authority }}
    -sha256 -subj
    '/C={{ csr_country_name }}/ST={{ csr_state_or_province_name }}/L={{ csr_locality_name }}/O={{ csr_organization_name }}/CN=self-sign.{{ roles_common_domain_name }}'
  args:
    creates: '{{ path_file_certificate_server_request_certificate_authority }}'

- name: certificate authority by myself
  command: >
    openssl x509
    -in {{ path_file_certificate_server_request_certificate_authority }}
    -days 36500 -req
    -signkey {{ path_file_secret_key_certificate_authority }}
    -out {{ path_file_certificate_self }}
  args:
    creates: '{{ path_file_certificate_self }}'

- name: create index.txt to certificate authority
  file:
    path: /etc/pki/CA/index.txt
    state: touch
    owner: root
    group: root
    mode: 0600

- name: set serial to certificate authority
  template:
    src: serial.j2
    dest: /etc/pki/CA/serial
    owner: root
    group: root
    mode: 0600
